pub struct CorpusEntry {
    pub id: &'static str,
    pub origin: &'static str,
    pub command: &'static str,
}

macro_rules! c {
    ($id:literal, $origin:literal, $command:literal) => {
        CorpusEntry { id: $id, origin: $origin, command: $command }
    };
}

// Commands are copied or normalized from the bash_permissions and bash_rewrite
// integration/unit tests. A normalized temporary path keeps this probe portable
// while preserving the shell syntax being tested.
pub static CORPUS: &[CorpusEntry] = &[
    c!("perm-echo", "permission-test", "echo hello"),
    c!("perm-cat-temp", "permission-test", "cat /tmp/aft-bash-temp-exemption.txt"),
    c!("perm-cat-hosts", "permission-test", "cat /etc/hosts"),
    c!("perm-redirect", "permission-test", "echo hi > /tmp/aft-redirect/out"),
    c!("perm-dynamic-redirect", "permission-test", "echo hi > $OUTFILE"),
    c!("perm-dynamic-file", "permission-test", r#"rm "$DEST/file""#),
    c!("perm-relative-redirect", "permission-test", "echo hi > ./file.log"),
    c!("perm-source", "permission-test", "source /tmp/aft-source.sh"),
    c!("perm-dot-source", "permission-test", ". /tmp/aft-dot-source.sh"),
    c!("perm-symlink", "permission-test", "rm link/secret.txt"),
    c!("perm-chain", "permission-test", "cd /tmp/aft-chain && rm foo"),
    c!("perm-git", "permission-test", "git status"),
    c!("perm-pipe", "permission-test", "find . | xargs grep foo"),
    c!("perm-grant", "permission-test", "git status --short"),
    c!("perm-background", "permission-test", "rm /tmp/aft-background-permission-test.txt"),
    c!("perm-malformed", "permission-test", "echo 'unterminated"),
    c!("perm-basic-ls", "permission-test", "ls -la"),
    c!("perm-basic-find", "permission-test", "find . -name foo"),
    c!("perm-basic-cat", "permission-test", "cat README.md"),
    c!("perm-set", "permission-test", "set -e"),
    c!("perm-shopt", "permission-test", "shopt -s nullglob"),
    c!("perm-type", "permission-test", "type git"),
    c!("perm-alias", "permission-test", "alias"),
    c!("perm-pure-redirect", "permission-test", "> /tmp/x"),
    c!("perm-colon", "permission-test", ":"),
    c!("perm-colon-redirect", "permission-test", ": > /tmp/x"),
    c!("perm-assignment", "permission-test", "FOO=bar"),
    c!("perm-arithmetic", "permission-test", "((i++))"),
    c!("perm-extended-test", "permission-test", "[[ -f foo ]]"),
    c!("perm-readonly", "permission-test", "readonly FOO=bar"),
    c!("perm-declare-array", "permission-test", "declare -A map=()"),
    c!("perm-subshell", "permission-test", "(ls)"),
    c!("perm-brace-group", "permission-test", "{ ls; }"),
    c!("perm-dollar-subst", "permission-test", "$(ls)"),
    c!("perm-backtick-subst", "permission-test", "`ls`"),
    c!("perm-eval", "permission-test", "eval ls"),
    c!("perm-bash-c", "permission-test", "bash -c ls"),
    c!("perm-pipe-head", "permission-test", "ls | head"),
    c!("perm-heredoc", "permission-test", "cat <<EOF\nhi\nEOF"),
    c!("perm-unicode-space", "permission-test", "git\u{00a0}status"),
    c!("perm-pwd", "scan-unit-test", "$PWD/output.log"),
    c!("perm-dev-null", "scan-unit-test", "echo test 2>/dev/null"),
    c!("perm-dev-stderr", "scan-unit-test", "some-command 2>/dev/stderr"),
    c!("perm-dev-fd", "scan-unit-test", "cat /dev/fd/2"),
    c!("perm-dev-fd-path", "scan-unit-test", "cat /dev/fd/../sda"),

    c!("rewrite-grep", "rewrite-test", "grep -ni needle /tmp/project/src"),
    c!("rewrite-grep-pipe", "rewrite-test", "grep needle src | wc -l"),
    c!("rewrite-grep-flag", "rewrite-test", "grep -x needle src"),
    c!("rewrite-grep-regex", "rewrite-test", "grep '(a?){500000}' /tmp/project"),
    c!("rewrite-rg", "rewrite-test", "rg alpha /tmp/project"),
    c!("rewrite-rg-chain", "rewrite-test", "rg alpha . && echo done"),
    c!("rewrite-find", "rewrite-test", "find src -name '*.rs' -type f"),
    c!("rewrite-find-flag", "rewrite-test", "find src -maxdepth 1 -name '*.rs'"),
    c!("rewrite-cat", "rewrite-test", "cat /tmp/project/a.txt"),
    c!("rewrite-cat-multi", "rewrite-test", "cat a.txt b.txt"),
    c!("rewrite-cat-heredoc", "rewrite-test", "cat >> notes.txt <<EOF\nfirst\nEOF"),
    c!("rewrite-echo-append", "rewrite-test", "echo \"second line\" >> notes.txt"),
    c!("rewrite-cat-write", "rewrite-test", "cat > notes.txt"),
    c!("rewrite-echo-session", "rewrite-test", "echo scoped >> /tmp/project/notes.txt"),
    c!("rewrite-sed", "rewrite-test", "sed -n '2,3p' /tmp/project/lines.txt"),
    c!("rewrite-sed-other", "rewrite-test", "sed 's/two/TWO/' lines.txt"),
    c!("rewrite-ls", "rewrite-test", "ls -a /tmp/project/src"),
    c!("rewrite-ls-flag", "rewrite-test", "ls -h src"),
    c!("rewrite-ls-long", "rewrite-test", "ls -l /tmp/project/src"),
    c!("rewrite-ls-file-long", "rewrite-test", "ls -l /tmp/project/README.md"),
    c!("rewrite-ls-file", "rewrite-test", "ls /tmp/project/README.md"),
    c!("rewrite-ls-missing", "rewrite-test", "ls /tmp/project/does-not-exist"),
    c!("rewrite-outside-cat", "rewrite-test", "cat /tmp/outside/outside.txt"),
    c!("rewrite-outside-sed", "rewrite-test", "sed -n '1,1p' /tmp/outside/outside.txt"),
    c!("rewrite-outside-ls", "rewrite-test", "ls /tmp/outside"),
    c!("rewrite-outside-grep", "rewrite-test", "grep -n secret /tmp/outside"),
    c!("rewrite-parser-quotes", "rewrite-parser-test", "grep 'two words' \"src dir\""),
    c!("rewrite-parser-escape", "rewrite-parser-test", r"cat file\ name.txt"),
    c!("rewrite-parser-heredoc", "rewrite-parser-test", "cat >> out.txt <<EOF\nhello\nEOF"),
    c!("rewrite-parser-command-subst", "rewrite-parser-test", "cat $(pwd)"),
    c!("rewrite-parser-backtick", "rewrite-parser-test", "cat `pwd`"),
    c!("rewrite-parser-variable", "rewrite-parser-test", "echo $HOME"),

    // Adversarial additions: command-name construction, expansion, nested
    // evaluation, compound commands, and redirect/process-substitution forms.
    c!("adv-echo-subst", "adversarial", "echo$(id)"),
    c!("adv-echo-ifs", "adversarial", "echo${IFS}id"),
    c!("adv-echo-semi", "adversarial", "echo safe; id"),
    c!("adv-echo-and", "adversarial", "echo safe && id"),
    c!("adv-echo-or", "adversarial", "true || id"),
    c!("adv-nested-subst", "adversarial", "echo $(printf '%s' \"$(id)\")"),
    c!("adv-backtick-nested", "adversarial", "echo `printf '%s' \"$(id)\"`"),
    c!("adv-assignment-subst", "adversarial", "x=$(id); echo \"$x\""),
    c!("adv-ifs-command", "adversarial", "${IFS}id"),
    c!("adv-variable-command", "adversarial", "CMD=id; $CMD"),
    c!("adv-indirect-command", "adversarial", "CMD=id; ${!CMD}"),
    c!("adv-eval", "adversarial", "eval \"id /tmp/x\""),
    c!("adv-bash-c", "adversarial", "bash -c 'id /tmp/x'"),
    c!("adv-sh-c", "adversarial", "sh -c \"cat /etc/hosts\""),
    c!("adv-array-invoke", "adversarial", "cmd=(id /tmp/x); \"${cmd[@]}\""),
    c!("adv-array-declare", "adversarial", "declare -a cmd=(id /tmp/x); \"${cmd[@]}\""),
    c!("adv-for", "adversarial", "for x in a b; do rm \"$x\"; done"),
    c!("adv-if", "adversarial", "if true; then rm /tmp/x; fi"),
    c!("adv-case", "adversarial", "case x in x) rm /tmp/x;; esac"),
    c!("adv-brace", "adversarial", "{ echo before; rm /tmp/x; }"),
    c!("adv-subshell", "adversarial", "(cd /tmp && cat /etc/hosts)"),
    c!("adv-process-subst", "adversarial", "cat <(cat /etc/hosts)"),
    c!("adv-redirect-subst", "adversarial", "echo hi > $(printf /tmp/x)"),
    c!("adv-tee-subst", "adversarial", "echo hi 2> >(tee /tmp/log)"),
    c!("adv-herestring", "adversarial", "cat <<< \"$(id)\""),
    c!("adv-redir-hang", "adversarial", "cat < $((1 + 2))"),
    c!("adv-windows-path", "adversarial", "printf '%s\\n' 'C:\\Users\\alice\\file.txt'"),
    c!("adv-windows-arg", "adversarial", "git --work-tree=C:\\repo status"),
    c!("adv-parameter-default", "adversarial", "${CMD:-id} /tmp/x"),
    c!("adv-parameter-transform", "adversarial", "${PATH##*/} /tmp/x"),
    c!("adv-arithmetic", "adversarial", "(( $(id) ))"),
];
